### ISSUE TITLE
Print NVMe version of controller/firmware

### ISSUE THREAD

**Issue by paulmenzel** [linux-nvme/nvme-cli#1143]
Some properties depend on the NVMe version. Linux has the check below in `drivers/nvme/host/core.c`:

                    if (ctrl->vs >= NVME_VS(1, 2, 1))
                            dev_warn(ctrl->device, "missing or invalid SUBNQN field.\n");

How to I print the NVMe version with `nvme-cli`? Is it `ver` in the `id-ctrl` output below?

    $ ./nvme version
    nvme version 1.14.68.g24dd
    $ sudo ./nvme id-ctrl /dev/nvme0n1
    […]
    ver       : 0x10200
    […]

**Comment by birkelund** [comment]
Yes, the version is packed as four bytes (`0x00010000 | 0x0200 | 0x00`) in your case. Aka, version v1.2.0.

The same information is also available in the `VS` register (see `nvme show-regs`).

**Comment by paulmenzel** [comment]
Thank you.

**Comment by keithbusch** [comment]
The spec compliance version is indeed noted in the Identify Controller "ver" field for 1.2 and later (the field didn't exist prior to 1.2), and in the "VS" register. However, most kernels do not support the "show-regs" command since they don't allow user space to mmap a device's IO memory space if a driver is bound to it.
