### ISSUE TITLE
Add support for Identify data structure with CNS values 02h, 11h and 12h

### ISSUE THREAD

**Issue by kpooja88** [linux-nvme/nvme-cli#138]
It would be very helpful if you could add separate commands for Identify data structures for above CNS values, I think what is supported right now is 00h (id-ns), 01h (id-ctrl), 10h (list-ns) and 13h (list-ctrl) as per NVMe spec 1.2. !!

**Comment by keithbusch** [comment]
These are all different modes of the existing commands. You get CNS=2 with nvme list-ns --all. You get CNS=11h with nvme id-ns --force. And you get CNS=12h with nvme id-ctrl --namespace-id=<nsid>.

**Comment by kpooja88** [comment]
Great..thanks!

**Comment by hellotwozeroonethree** [comment]
thank you so much来自我的华为平板电脑-------- 原始邮件 --------主题：Re: [linux-nvme/nvme-cli] Add support for Identify data structure with CNS values 02h, 11h and 12h (#138)发件人：Keith Busch 收件人：linux-nvme/nvme-cli 抄送：These are all different modes of the existing commands. You get CNS=2 with nvme list-ns --all. You get CNS=11h with nvme id-ns --force. And you get CNS=12h with nvme id-ctrl --namespace-id=.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/linux-nvme/nvme-cli","title":"linux-nvme/nvme-cli","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/linux-nvme/nvme-cli"}},"updates":{"snippets":[{"icon":"PERSON","message":"@keithbusch in #138: These are all different modes of the existing commands. You get CNS=2 with nvme list-ns --all. You get CNS=11h with nvme id-ns --force. And you get CNS=12h with nvme id-ctrl --namespace-id=\u003cnsid\u003e."}],"action":{"name":"View Issue","url":"https://github.com/linux-nvme/nvme-cli/issues/138#issuecomment-258168928"}}}</sc
 ript></blockquote></div>
