### ISSUE TITLE
NS_ID_UNAVAILABLE

### ISSUE THREAD

**Issue by five-5** [linux-nvme/nvme-cli#1972]
# Question
I try to create multi namespace on one device, but when I first delete original namespace and create second namespace, it reports `NVMe Status:NS_ID_UNAVAILABLE: The number of namespaces supported has been exceeded(2116)`. Complete operation as follows：
```
root@:~# nvme delete-ns /dev/nvme0n1
delete-ns: Success, deleted nsid:1
root@:~# nvme create-ns /dev/nvme0 --nsze=20971520 --ncap=20971520 --flbas=0 --dps=0 
create-ns: Success, created nsid:1
root@:~# nvme create-ns /dev/nvme0 --nsze=20971520 --ncap=20971520 --flbas=0 --dps=0 
NVMe Status:NS_ID_UNAVAILABLE: The number of namespaces supported has been exceeded(2116)
```

# Information
```
root@:~# nvme list
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev  
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1     S4YKNA0N205174       SAMSUNG MZQLB1T9HAJR-000TC               1           0.00   B /   0.00   B      1   B +  0 B   EDA55T0Q
/dev/nvme1n1     S4YKNA0N204933       SAMSUNG MZQLB1T9HAJR-000TC               1           0.00   B /  10.74  GB    512   B +  0 B   EDA55T0Q
/dev/nvme2n1     S4YKNA0N205130       SAMSUNG MZQLB1T9HAJR-000TC               1         879.25  MB /   1.80  TB      4 KiB +  0 B   EDA55T0Q
/dev/nvme3n1     S4YKNA0N205042       SAMSUNG MZQLB1T9HAJR-000TC               1         879.25  MB /   1.80  TB      4 KiB +  0 B   EDA55T0Q
```

# What I want
I want to know if there any command for query the maximum number of namespace supports by the device or what I can do to deal with the `NS_ID_UNAVAILABLE`

**Comment by keithbusch** [comment]
Many do only support single namespace, but I'm surprised any of those support namespace management in that case! What's the point?! :)

It looks like some weird device handles are appearing through the kernel, though: it's showing a 0 capacity namespace on nvme0. It probably shouldn't show up in the 'list' since the attach-ns command wasn't run.

**Comment by five-5** [comment]
> Forgot to mention `mnan`. So you need to check both fields
> 
> > Maximum Number of Allowed Namespaces (MNAN): This field indicates the
> > maximum number of namespaces supported by the NVM subsystem. If this field is
> > cleared to 0h, then the maximum number of namespaces supported by the NVM
> > subsystem is less than or equal to the value in the NN field. If the controller supports
> > Asymmetric Namespace Access Reporting, then this field shall be set to a non-zero
> > value that is less than or equal to the NN value.
> 
> As far I know (doesn't mean a lot :)) most consumer grade SSD will only support one namespace.

Thanks, it helps a lot.

**Comment by five-5** [comment]
> Many do only support single namespace, but I'm surprised any of those support namespace management in that case! What's the point?! :)
> 
> It looks like some weird device handles are appearing through the kernel, though: it's showing a 0 capacity namespace on nvme0. It probably shouldn't show up in the 'list' since the attach-ns command wasn't run.

1. For this purpose, we have a machine only has six devices, and we use these devices in k8s as LPV, we want more pods on one machine and also have some isolation of data on one device. So, I just try to use the "namespace" feature to find out whether it works.
2. I also feel weird about the `nvme list` results, but I do not know whether it is normal or not.

**Comment by igaw** [comment]
I think creating partitions should give you the same level of data separation as namespaces from the userspace point of view. One could argue by using namespaces you enforce the separation on firmware level instead in the kernel gives you better 'protection'. If the kernel is not misbehaving due to bugs, you should get the semantics semantics. As the partition code is really well tested and your tests have shown that the namespaces are not likely to work in the firmware, I would suggest to use partitions. 

`nvme list` results look like the kernel is a bit confused. This is better reported directly on the upstream linux-nvme mailing list.
