### ISSUE TITLE
How to use nvme resv-register/acquire/release commands?

### ISSUE THREAD

**Issue by wuwenjuncool** [linux-nvme/nvme-cli#211]
I have use identify tools to check the intel D3700/P3700/P4500  all of these not support nvme security-send and nvme security-recv command.  Does these ssd  support  nvme resv-register/acquire/release commands? If support, it's great if anyone can give me a example to run these commands. And What kindof SSD support nvme security-send and nvme security-recv？(I want to test all commands of nvme-cli and try my best to add a Example to Users,you konw,nvme-cli has so many argv ,if --help options without a Example it's hardly for user to run it.) For me I have try so many argv to run nvme resv-register command but still failed:
waikiki5-target:~# nvme resv-register /dev/nvme0n1  -n 1 -c 1 -k 1 -r 1 -p 1 -i 
NVME IO command error:INVALID_OPCODE(1)

Thanks

**Comment by keithbusch** [comment]
Reservations are only useful on multi-controller/multi-path NVMe subsystems. All of the models you mentioned are single-controller.

The P4800X supports security commands, implementing the Opal specification. I wouldn't necessarily recommend using nvme-cli for security though, since nvme doesn't define protocol, meaning you need to generate your payloads with a different program to thread through nvme-cli. The "sedutil" program can do that all within a single tool.
