### ISSUE TITLE
nvme set-feature quietly fails to set the power mode

### ISSUE THREAD

**Issue by eosolid** [linux-nvme/nvme-cli#2209]
In the past I was able to use nvme-cli to set the different power modes allowed by the nvme device. Latest version of nvme-cli seems to be working fine and commands are running successfully, but they don't take effect. Last tested working version was on 2.2.1.
I tried this same procedure on version 2.6 and on master ( as today) and still fails to update the power mode of the nvme device.

Working version 2.2.1
![fio_PS_0_nvme2-2-1](https://github.com/linux-nvme/nvme-cli/assets/159199571/374f2b44-22f6-4837-a790-ee4a6731364f)
![fio_PS_2_nvme2-2-1](https://github.com/linux-nvme/nvme-cli/assets/159199571/c384b08a-204f-450f-823c-0f07479a2736)

Failing to set the correct power mode on 2.6
![PS_2_nvme_6-1_no_effect](https://github.com/linux-nvme/nvme-cli/assets/159199571/467f70d1-7f78-4d7a-bb93-128e665e35fc)

Failing to set the correct power mode on master ( tested today as 2/6/24 )
![fio_PS_0_nvme_master](https://github.com/linux-nvme/nvme-cli/assets/159199571/7810a4f7-01be-478e-9779-19de83a845f7)
![fio_PS_2_nvme_master](https://github.com/linux-nvme/nvme-cli/assets/159199571/fad96091-739c-4189-903a-847469632835)

**Comment by keithbusch** [comment]
Because some of the short parameters got hijacked for other purposes... The '-v' parameter now means "verbose" instead of "value". If you want it to work again, you'll need to replace your '-v' option with '--value' or use capital '-V'.

Yes, I know these types of changes are annoying and harm confidence in consistency. I cautioned against changing args because of the destruction to backward compatibility, and @igaw agreed in a different thread that we won't be doing such changes anymore.

**Comment by keithbusch** [comment]
When in doubt, run --help:

```
$ ./.build/nvme set-feature --help
Usage: nvme set-feature <device> [OPTIONS]

Options:
  [  --verbose, -v ]                    --- Increase output verbosity
...
  [  --value=<IONUM>, -V <IONUM> ]      --- new value of feature (required)
```
