### ISSUE TITLE
nvme-cli: code style

### ISSUE THREAD

**Issue by tim-oleksii** [linux-nvme/nvme-cli#301]
Hello everyone,

Could you please help me?
Are there any suggestions regarding the plugin code style? Spaces vs tabs, etc...

Thank you!

**Comment by keithbusch** [comment]
This project has generally adopted the Linux kernel coding style (except for the 80-column lines, due to argconfig's verbosity...).

https://www.kernel.org/doc/html/v4.15/process/coding-style.html

This is not strictly enforced on vendor extensions, though. Some were ported from vendor specific tools with different styles, and I didn't want to bikeshed adopting the extensions for consistency.

I'd still prefer Linux style for anything that's starting from scratch or anything in the common code.

**Comment by tim-oleksii** [comment]
Thank you!
