### ISSUE TITLE
NVMe State Code not match spec?

### ISSUE THREAD

**Issue by JasonChiuCC** [linux-nvme/nvme-cli#382]
Hi, My deivce is  Intel Corporation PCIe Data Center SSD (rev 01)
When I use command below :
sudo ./nvme get-log /dev/nvme0 -n 1 -i 0 -l 64
and return
INVALID_LOG_PAGE: The log page indicated is invalid. 
This error condition is also returned if a reserved log page is requested(109)

But in NVMe Spec 1.3a Page70
Status Code – Command Specific Status Values
09h = Invalid Log Page 

So Which is correct? 0x109 or 0x9 ??
Thanks

**Comment by keithbusch** [comment]
The response your getting sounds right since you're not specifying a log page, so it defaults to 0 which is indeed invalid.

The spec is a bit odd in how it lays out the status codes. You'll need to dig a little deeper to see why 0x109 is the correct status here.

The layout of the completion 15-bit status field is laid out in section 4.6.1. The "0x9" part you're referring to is the lower 8-bit "SC" field, which is a sub-category of the "status code type", the 3-bit SCT field. For this type, the SCT field is '1', or "Command Specific Error" status type. Combining these, we get the full status field of 0x109 (masking off the meta-status fields).
