### ISSUE TITLE
What is the "flags" parameter for io-passthru command?

### ISSUE THREAD

**Issue by candicezero** [linux-nvme/nvme-cli#399]
In the Document for the nvme-io-passthru command, there is a parameter "flags" which has only very little information. I searched the whole NVME Spec but could not find anything called "NVME flag".
Following is what the document says:
**-f <flags> 
--flags=<flags> 
The NVMe command flags to send to the device in the command** 
But this is really not helpful at all. I do not know what should be passed in for this parameter, and there is no example in either the doc or the sample test cases.
Can this Document be updated with a little bit more details on it?

**Comment by keithbusch** [comment]
It represents the second byte of command dword 0. The spec provides these to flag special operations of the command, like the data transfer format and for fused operations.

The linux kernel (at least anything recent) will not allow you to set these because it currently can't work with them. It's really only existing in the tool for future use since the kernel provided this in the ioctl structure since its inception even though it can't use them.
