### ISSUE TITLE
display Idle (Active) Power on Power State Descriptor Data Structure

### ISSUE THREAD

**Issue by Dong-Jun** [linux-nvme/nvme-cli#85]
Hi, All

Maybe, there was a mistake to display Idle Power and Active Power.
In the NVMe Spec 1.2, Idle Power Scale is displayed with bit 151:150.
But in the source code, idle power scale argument is parsed with bitwise & 0x0.
I think idle power scale value is extracted with 0xC0.

**Comment by keithbusch** [comment]
I think I see what you're saying, though the code uses 0x3 rather than 0x0.

Odd the spec chose to reserve the lower bits, instead occupying the upper bits for this field. Looks like it'll require some creative encoding if the committee needs to use a reserved bit for more scales.

The code's active power scale is also broken, using defined bits for the wrong purpose ...

Anyway, thanks for the catch, I'll push a fix.
